name: 'Execute Terraform'

on: [push, pull_request, workflow_dispatch]

env:
  TF_LOG: INFO
  GITHUB_OWNER: ${{ secrets.GIT_OWNER }}
  GITHUB_TOKEN: ${{ secrets.GIT_PAT }}

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    # Set the working directory to main for the config files
    defaults:
      run:
        shell: bash
        working-directory: ./main

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Install Terraform CLI 
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    # Terraform init
    - name: Terraform Init
      id: init
      run: terraform init

    # Run a terraform plan
    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
    
    # Terraform Apply
    - name: Terraform Apply
      run: terraform apply -auto-approve
