name: 'Execute Terraform'

on: [push, pull_request, workflow_dispatch]

env:
  TF_LOG: INFO
  passphraseFile: ${{ secrets.FILE_PASS_PHRASE }}
  GITHUB_OWNER: ${{ secrets.GIT_OWNER }}
  GITHUB_TOKEN: ${{ secrets.GIT_PAT }}

jobs:
  call-workflow-using-branch:
    uses: BJuarez-Integration-Academy/greetings-app/.github/workflows/main.yml@dev
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    # Set the working directory to main for the config files
    defaults:
      run:
        shell: bash
        working-directory: ./main

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    - name: Decrypt and read file
      run: gpg --quiet --batch --yes --decrypt --passphrase="$passphraseFile" --use-embedded-filename *.json.gpg

    # Install Terraform CLI 
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    # Terraform init
    - name: Terraform Init
      id: init
      run: terraform init

      #Terraform Validate
    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    # Run a terraform plan
    - name: Terraform Plan
      id: plan
      run: terraform plan -compact-warnings -no-color
    
    # Terraform Apply
    - name: Terraform Apply
      run: terraform apply -compact-warnings -auto-approve
